const portfolioImageGroups = [
  {
    category: 'Commercial',
    featuredImage: '/images/commercial/DSC_3525-1.webp',
    paths: [
      '/images/commercial/fliq Media.jpg',
      '/images/commercial/fliq Media 1.jpg',
      '/images/commercial/fliq Media 2.jpg',
      '/images/commercial/fliq Media 3.jpg',
      '/images/commercial/fliq Media 4.jpg',
      '/images/commercial/fliq Media 5.jpg',
      '/images/commercial/fliq Media 6.jpg',
      '/images/commercial/fliq Media 7.jpg',
      '/images/commercial/fliq Media 8.jpg',
      '/images/commercial/DSC05147.jpg',
      '/images/commercial/DSC05207.jpg',
      '/images/commercial/DSC05209.jpg',
      '/images/commercial/FliQ Media 33.jpg',
      '/images/commercial/FliQ Media 39.jpg',
      '/images/commercial/FliQ Media 40.jpg',
      '/images/commercial/FliQ Media 41.jpg',
      '/images/commercial/2A7301518.JPG',
      '/images/commercial/DSC_3511.JPG',
      '/images/commercial/DSC_3525-1.JPG',
      '/images/commercial/DSC_3527-1.JPG',
      '/images/commercial/DSC_3746.JPG',
      '/images/commercial/DSC03481.JPG',
      '/images/commercial/DSC03489.JPG',
      '/images/commercial/fliq Media 372.JPG',
      '/images/commercial/fliq Media 377.JPG',
      '/images/commercial/FliQ Media X Genti 261 10.37.09 am.JPG',
      '/images/commercial/FliQ Media X Genti 261 10.41.43 am.JPG',
      '/images/commercial/FliQ Media X Genti 274.JPG',
      '/images/commercial/FliQ-Media-Pictures-266.JPG',
      '/images/commercial/FliQ-Media-Pictures-269.JPG',
      '/images/commercial/IMG_1638.JPG',
    ],
  },
  {
    category: 'Corporate Headshots',
    featuredImage: '/images/corporateheadshots/IMG_4929.JPG.jpeg',
    paths: [
      '/images/corporateheadshots/337fb0d9-a48f-47cb-8a46-68eb65197d3c.jpg',
      '/images/corporateheadshots/4c657dd6-eee9-4ac9-9d91-9330d61c9585.jpg',
      '/images/corporateheadshots/BUSOLAMI-MARTINS-.JPG',
      '/images/corporateheadshots/DSC02301.JPG',
      '/images/corporateheadshots/DSC03416-Recovered-Recovered.JPG',
      '/images/corporateheadshots/DSC03571.JPG',
      '/images/corporateheadshots/DSC03579.JPG',
      '/images/corporateheadshots/DSC08784.JPG',
      '/images/corporateheadshots/DSC08990.JPG',
      '/images/corporateheadshots/DSC09187.JPG',
      '/images/corporateheadshots/DSC09287.JPG',
      '/images/corporateheadshots/IMG_4929.JPG.jpeg',
      '/images/corporateheadshots/kDSC09589.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20260015-2-Recovered.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20260122.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20260149.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20260359-Recovered.jpg',
      '/images/corporateheadshots/Leap-Africa-HS.-20261292-Recovered.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20262442-1.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20262675-Recovered-Recovered-Recovered.JPG',
      '/images/corporateheadshots/Leap-Africa-HS.-20264781.JPG',
      '/images/corporateheadshots/Leap-Africakeep 2.JPG',
    ],
  },
  {
    category: 'Editorial',
    featuredImage: '/images/editorial/301521.webp',
    paths: [
      '/images/editorial/301521.JPG',
      '/images/editorial/301535-1.JPG',
      '/images/editorial/301638.JPG',
      '/images/editorial/301639.JPG',
      '/images/editorial/301793.JPG',
      '/images/editorial/301797.JPG',
      '/images/editorial/Creatorr07086.JPG',
      '/images/editorial/creatorr-C06979.jpg',
      '/images/editorial/DSC02092.JPG',
      '/images/editorial/DSC05547.jpg',
      '/images/editorial/DSC05589.jpg',
      '/images/editorial/DSC07041.JPG',
      '/images/editorial/fliq-125.JPG',
      '/images/editorial/fliqmedia-3.JPG',
      '/images/editorial/image00001.JPEG',
      '/images/editorial/image00006.JPEG',
      '/images/editorial/image00011.JPEG',
      '/images/editorial/image00013.JPEG',
      '/images/editorial/King07040.JPG',
      '/images/editorial/king-07043.JPG',
      '/images/editorial/king081.JPG',
      '/images/editorial/King-7079.JPG',
      '/images/editorial/king-7081.JPG',
      '/images/editorial/kingDSC06617.JPG',
    ],
  },
  {
    category: 'Events',
    featuredImage: '/images/events/TECH 14.webp',
    paths: [
      '/images/events/A7309822.JPG',
      '/images/events/FliQ Media 183.JPEG',
      '/images/events/FliQ Media 19.JPEG',
      '/images/events/FliQ Media 2 10.49.24 am.JPG',
      '/images/events/FliQ Media 252.JPEG',
      '/images/events/FliQ Media 26.JPEG',
      '/images/events/FliQ Media 28.JPG',
      '/images/events/FliQ Media 321.JPEG',
      '/images/events/FliQ Media 405.JPEG',
      '/images/events/FliQ Media 417.JPG',
      '/images/events/FliQ Media 423 10.49.24 am.JPG',
      '/images/events/FliQ Media 427.JPEG',
      '/images/events/FliQ Media 475.JPEG',
      '/images/events/FliQ Media 54.JPG',
      '/images/events/FliQ Media 60.JPG',
      '/images/events/FliQ Media Pictures 12.JPG',
      '/images/events/FliQ Media Pictures 13.JPG',
      '/images/events/FliQ Media Pictures 14.JPG',
      '/images/events/FliQ Media Pictures 16.JPG',
      '/images/events/FliQ Media Pictures 31.JPG',
      '/images/events/FliQ Media Pictures 36.JPG',
      '/images/events/FliQ-Media-X-Genti-131.JPG',
      '/images/events/FliQ-Media-X-Genti-159.JPG',
      '/images/events/TECH 14.JPG',
      '/images/events/TECH 29.JPG',
      '/images/events/TECH 44.JPG',
      '/images/events/TECH 45.JPG',
    ],
  },
  {
    category: 'Lifestyle',
    featuredImage: '/images/lifestyle/DSC08650.webp',
    paths: [
      '/images/lifestyle/A7309828.JPG',
      '/images/lifestyle/DSC_t654521.JPG',
      '/images/lifestyle/DSC00968-1.JPG',
      '/images/lifestyle/DSC00970-1.JPG',
      '/images/lifestyle/DSC01063-1.JPG',
      '/images/lifestyle/DSC01064-1.JPG',
      '/images/lifestyle/DSC01067-1.JPG',
      '/images/lifestyle/DSC02254.JPG',
      '/images/lifestyle/DSC08067.JPG',
      '/images/lifestyle/DSC08076.JPG',
      '/images/lifestyle/DSC08222.JPG',
      '/images/lifestyle/DSC08650.JPG',
      '/images/lifestyle/DSC08655.JPG',
      '/images/lifestyle/DSC08701.JPG',
      '/images/lifestyle/DSC08809.JPG',
      '/images/lifestyle/DSC08839.JPG',
      '/images/lifestyle/DSC08855.JPG',
      '/images/lifestyle/DSC09336-2 2.JPG',
      '/images/lifestyle/DSC09416.JPG',
      '/images/lifestyle/FliQ Media 10 10.47.42 am.JPG',
      '/images/lifestyle/FliQ Media 10.47.42 am.JPG',
      '/images/lifestyle/FliQ Media 16 10.47.42 am.JPG',
      '/images/lifestyle/FliQ Media 168.JPG',
      '/images/lifestyle/FliQ Media 170.JPG',
      '/images/lifestyle/FliQ Media 230.JPG',
      '/images/lifestyle/FliQ Media 236.JPG',
      '/images/lifestyle/FliQ Media 332.JPG',
      '/images/lifestyle/FliQ Media 337.JPG',
      '/images/lifestyle/FliQ Media 345.JPG',
      '/images/lifestyle/fliq Media 363.JPG',
      '/images/lifestyle/fliq Media 366.JPG',
      '/images/lifestyle/fliq Media 412.JPG',
      '/images/lifestyle/FliQ Media 502.JPG',
      '/images/lifestyle/FliQ Media Pictures 222.JPG',
      '/images/lifestyle/FliQ Media Pictures 227.JPG',
      '/images/lifestyle/FliQ Media Pictures 484.JPG',
      '/images/lifestyle/FliQ Media Pictures 580.JPG',
      '/images/lifestyle/FliQ Media Pictures 75.JPG',
      '/images/lifestyle/FliQ Media Pictures 9.JPG',
      '/images/lifestyle/FliQ Media X Genti 149.JPG',
      '/images/lifestyle/FliQ Media X Genti 150 10.47.42 am.JPG',
      '/images/lifestyle/FliQ Media X Genti 163.JPG',
      '/images/lifestyle/FliQ Media X Genti 167.JPG',
      '/images/lifestyle/FliQ Media X Genti 303.JPG',
      '/images/lifestyle/FliQ Media X Genti 4.JPG',
      '/images/lifestyle/Fliq-Media-.JPG',
      '/images/lifestyle/fliq-media-1.JPG',
      '/images/lifestyle/FliQMediaPictures149 10.47.42 am.JPG',
      '/images/lifestyle/FliQMediaPictures152 10.47.42 am.JPG',
      '/images/lifestyle/FliQMediaPictures185.JPG',
      '/images/lifestyle/FliQMediaPictures188.JPG',
      '/images/lifestyle/FliQMediaPictures191.JPG',
      '/images/lifestyle/FliQMediaPictures213.JPG',
      '/images/lifestyle/KE9511.JPG',
      '/images/lifestyle/MJP_1385.JPG',
    ],
  },
  {
    category: 'Music Concerts',
    featuredImage: '/images/musicconcerts/IMG_4850.webp',
    paths: [
      '/images/musicconcerts/8216EF41-10C8-49D5-8C92-986267A1D7D7 10.50.46 am.JPG',
      '/images/musicconcerts/B5FD1BF9-0FF3-42A2-9537-1FDBAB2D2590 10.50.46 am.JPG',
      '/images/musicconcerts/IMG_4850.JPG',
      '/images/musicconcerts/IMG_8798.JPG',
      '/images/musicconcerts/IMG_8799.JPG',
      '/images/musicconcerts/IMG_8800.JPG',
      '/images/musicconcerts/IMG_8802.JPG',
      '/images/musicconcerts/IMG_8803.JPG',
      '/images/musicconcerts/IMG_8805.JPG',
      '/images/musicconcerts/IMG_8806.JPG',
      '/images/musicconcerts/IMG_8807.JPG',
      '/images/musicconcerts/IMG_8808.JPG',
      '/images/musicconcerts/IMG_8809.JPG',
      '/images/musicconcerts/IMG_8950 10.50.46 am.jpg',
      '/images/musicconcerts/IMG_8952.jpg',
    ],
  },
  {
    category: 'Personal Branding',
    featuredImage: '/images/personalbrandingportraits/CHIOMA169.webp',
    paths: [
      '/images/personalbrandingportraits/25e4c7ff-1f00-404a-a32f-843269d1e871.jpg',
      '/images/personalbrandingportraits/30NEW8904.JPG',
      '/images/personalbrandingportraits/A7301205.JPG',
      '/images/personalbrandingportraits/A7301211.JPG',
      '/images/personalbrandingportraits/Amanda-Omogiafo.JPG',
      '/images/personalbrandingportraits/CHIOMA169(1).JPG',
      '/images/personalbrandingportraits/CHIOMA169.JPG',
      '/images/personalbrandingportraits/DSC00006-1.JPG',
      '/images/personalbrandingportraits/DSC00810-1.JPG',
      '/images/personalbrandingportraits/DSC00857.JPG',
      '/images/personalbrandingportraits/DSC00862.JPG',
      '/images/personalbrandingportraits/DSC01082.JPG',
      '/images/personalbrandingportraits/DSC01109.JPG',
      '/images/personalbrandingportraits/DSC01137-1.JPG',
      '/images/personalbrandingportraits/DSC02017.JPG',
      '/images/personalbrandingportraits/DSC02022.JPG',
      '/images/personalbrandingportraits/DSC02027.JPG',
      '/images/personalbrandingportraits/DSC02095-1.JPG',
      '/images/personalbrandingportraits/DSC02249.JPG',
      '/images/personalbrandingportraits/DSC05244-1.jpg',
      '/images/personalbrandingportraits/DSC05668.jpg',
      '/images/personalbrandingportraits/DSC05690.jpg',
      '/images/personalbrandingportraits/DSC09780-1.JPG',
      '/images/personalbrandingportraits/DSC09877.JPG',
      '/images/personalbrandingportraits/DSC6r09143.JPG',
      '/images/personalbrandingportraits/FliQ Media 445.JPG',
      '/images/personalbrandingportraits/FliQ Media 454.JPG',
      '/images/personalbrandingportraits/FliQ-Media-Poreait-1315.JPG',
      '/images/personalbrandingportraits/newd.jpg',
      '/images/personalbrandingportraits/newdebbie-2.jpg',
    ],
  },
  {
    category: 'Weddings',
    featuredImage: '/images/weddings/0V5A9921.webp',
    paths: [
      '/images/weddings/0V5A9921.JPG',
      '/images/weddings/0V5A9923.JPG',
      '/images/weddings/0V5A9953.JPG',
      '/images/weddings/78DSC00631.JPG',
      '/images/weddings/D22SC09447.JPG',
      '/images/weddings/DSC00038.JPG',
      '/images/weddings/DSC00039.JPG',
      '/images/weddings/DSC00412.JPG',
      '/images/weddings/DSC00431.JPG',
      '/images/weddings/DSC00631.JPG',
      '/images/weddings/DSC00632.JPG',
      '/images/weddings/DSC00727.JPG',
      '/images/weddings/DSC00795.JPG',
      '/images/weddings/DSC00799.JPG',
      '/images/weddings/DSC00800.JPG',
      '/images/weddings/DSC00803.JPG',
      '/images/weddings/DSC00826 10.44.00 am.JPG',
      '/images/weddings/DSC00860-1.JPG',
      '/images/weddings/DSC01853.JPG',
      '/images/weddings/DSC01856.JPG',
      '/images/weddings/DSC01859.JPG',
      '/images/weddings/DSC08913.JPG',
      '/images/weddings/DSC09033.JPG',
      '/images/weddings/DSC09279.JPG',
      '/images/weddings/DSC09282-1.JPG',
      '/images/weddings/DSC09283 2 10.44.00 am.JPG',
      '/images/weddings/DSC09299.JPG',
      '/images/weddings/DSC09306.JPG',
      '/images/weddings/DSC09336-3.JPG',
      '/images/weddings/DSC09403-1.JPG',
      '/images/weddings/DSC09469.JPG',
      '/images/weddings/DSC09497.JPG',
      '/images/weddings/DSC09539.JPG',
      '/images/weddings/DSC09615-1.JPG',
      '/images/weddings/DSC09639.JPG',
      '/images/weddings/DSC09805.JPG',
      '/images/weddings/DSC09807.JPG',
      '/images/weddings/DSC09847 2.JPG',
      '/images/weddings/DSC09847.JPG',
      '/images/weddings/DSC09949.JPG',
      '/images/weddings/IMG_1935.JPG',
      '/images/weddings/IMG_1942.JPG',
      '/images/weddings/IMG_2039.JPG',
      '/images/weddings/IMG_2078.JPG',
      '/images/weddings/J23_0681-2.JPG',
      '/images/weddings/keJ23_0485-1-1.JPG',
      '/images/weddings/keJ23_0704-2.JPG',
      '/images/weddings/MGW 10.49.56 am.JPG',
    ],
  },
] as const;

export const portfolioGenres = portfolioImageGroups.map(({ category, featuredImage }) => ({ category, image: featuredImage }));

export const portfolioImages = portfolioImageGroups.flatMap(({ category, paths }) =>
  paths.map((path) => ({
    category,
    path: category === 'Commercial' && [
      'DSC05147.jpg', 'DSC05207.jpg', 'DSC05209.jpg',
      'FliQ Media 33.jpg', 'FliQ Media 39.jpg', 'FliQ Media 40.jpg', 'FliQ Media 41.jpg',
      'fliq Media.jpg', 'fliq Media 1.jpg', 'fliq Media 2.jpg', 'fliq Media 3.jpg', 'fliq Media 4.jpg',
      'fliq Media 5.jpg', 'fliq Media 6.jpg', 'fliq Media 7.jpg', 'fliq Media 8.jpg',
    ].some((filename) => path.endsWith(`/${filename}`))
      ? path
      : path.replace(/\.(jpe?g)$/i, '.webp'),
  })),
);
